import os
import json
from services.queue_service import PikaClient
# from dohko.circuits.circuit import LayeredCircuit
# from dohko.prover.prover import ZkProver

async def verify_proof(consumer_id: str, proof_request_id: str, proof_provider: str, proof: str):
    print('Verifying proof for request ' + proof_request_id + ' using verifier: ' + consumer_id)

    pika_client = PikaClient(os.environ.get('RABBITMQ_URL'))

    await pika_client.publish("verifications_queue", json.dumps({
        'proof_request_id': proof_request_id,
        'proof': proof,
        'verification': 'verification for request ' + proof_request_id + ' generated by verifier: ' + consumer_id
    }))
