import os
import json
from protobuffer.Circuit_pb2 import Circuit
from services.protobuffer_service import json_to_protobuff, protobuff_to_json
from services.queue_service import PikaClient

async def generate_proof(consumer_id: str, proof_request_id: str, chunk_id, chunk: str):
    circuit = Circuit()
    circuit.ParseFromString(json_to_protobuff(chunk))

    # Generate proof for the chunk using "circuit"

    pika_client = PikaClient(os.environ.get('RABBITMQ_URL'))

    await pika_client.publish("proofs_queue", json.dumps({
        'proof_request_id': proof_request_id,
        'chunk_id': chunk_id,
        'proof': 'proof for chunk ' + str(chunk_id) + ' of proof request ' + proof_request_id + ' generated by worker: ' + consumer_id
    }))

    return None
