[tool.poetry]
name = "domain"
version = "0.1.0"
description = ""
authors = ["Andre Borges Medeiros <andborges@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
protobuf = "^5.27.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
