# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Circuit.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'Circuit.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rCircuit.proto\x12\x06\x44omain\"\x1c\n\nGateInputs\x12\x0e\n\x06inputs\x18\x01 \x03(\x05\"\x88\x01\n\x04Gate\x12$\n\x05ttype\x18\x01 \x01(\x0e\x32\x15.Domain.Gate.GateType\x12\"\n\x06inputs\x18\x02 \x03(\x0b\x32\x12.Domain.GateInputs\x12\x10\n\x03idx\x18\x03 \x01(\x05H\x00\x88\x01\x01\"\x1c\n\x08GateType\x12\x07\n\x03\x41\x44\x44\x10\x00\x12\x07\n\x03MUL\x10\x01\x42\x06\n\x04_idx\"+\n\x0c\x43ircuitLayer\x12\x1b\n\x05gates\x18\x01 \x03(\x0b\x32\x0c.Domain.Gate\"C\n\x07\x43ircuit\x12$\n\x06layers\x18\x01 \x03(\x0b\x32\x14.Domain.CircuitLayer\x12\x12\n\nnum_inputs\x18\x02 \x03(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Circuit_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GATEINPUTS']._serialized_start=25
  _globals['_GATEINPUTS']._serialized_end=53
  _globals['_GATE']._serialized_start=56
  _globals['_GATE']._serialized_end=192
  _globals['_GATE_GATETYPE']._serialized_start=156
  _globals['_GATE_GATETYPE']._serialized_end=184
  _globals['_CIRCUITLAYER']._serialized_start=194
  _globals['_CIRCUITLAYER']._serialized_end=237
  _globals['_CIRCUIT']._serialized_start=239
  _globals['_CIRCUIT']._serialized_end=306
# @@protoc_insertion_point(module_scope)
